---
title: "merge_NEON_tick"
author: "Tao Huang"
date: "October 8, 2019"
output: html_document
---

#SELECT FILES WITH "FIELDDATA" IN THEIR NAMES; SELECT FILES WITH "taxonomyProcessed" IN THEIR NAMES
```{r}
files<-list.files("/Users/owner/Downloads/get_ticks_data_from_NEON-master/output")
files<-as.data.frame(files)

fielddata<-files[grepl("fielddata",files$files),]
dim(files)
length(fielddata)

#taxonomyProcessed
taxonomyProcessed<-files[grepl("taxonomyProcessed",files$files),]
length(taxonomyProcessed)

```

#Merge data frames of taxonomyProcessed
```{r}
setwd("/Users/owner/Downloads/get_ticks_data_from_NEON-master/output")
q1<-as.character(taxonomyProcessed[1])
q1<-read.csv(q1)
df1<-q1

length(taxonomyProcessed)

for (q1 in taxonomyProcessed[2:length(taxonomyProcessed)])
{
  q1<-read.csv(q1)

  df1<-do.call("rbind", list(df1,q1))

}
  head(df1)
```


#MERGE DATA FRAMES OF fielddata
```{r}
setwd("/Users/owner/Downloads/get_ticks_data_from_NEON-master/output")
#fielddata: FILES WITH "FIELDDATA" IN THEIR NAMES
q<-as.character(fielddata[1])

q<-read.csv(q)

df<-q

length(fielddata)

for (q in fielddata[2:1035])
{
  q<-read.csv(q)

  df<-do.call("rbind", list(df,q))

}
df$decimalLongitude<-as.numeric(df$decimalLongitude)
df$decimalLatitude<-as.numeric(df$decimalLatitude)
df$elevation<-as.numeric(df$elevation)
df$totalSampledArea<-as.numeric(df$totalSampledArea)
```

#MERGE taxonomyProcessed AND Fielddata
```{r}
df_df1<-merge(df,df1,by= "sampleID")
dim(df_df1)
head(df_df1)

```

```{r}
save(df_df1,file="C:/Users/huangt/Documents/df_df1.Rdata")
```

```{r}

load("C:/Users/huangt/Documents/df_df1.Rdata")
head(df_df1)
```

#subset Dermacentor
```{r}
derm<-df_df1[df_df1$genus=="Dermacentor",]
derm<-derm[,c("siteID","sampleID","namedLocation.x","collectDate.y","individualCount","totalSampledArea"      ,"targetTaxaPresent","adultCount","nymphCount"            ,"larvaCount", "decimalLatitude"              ,"decimalLongitude"             ,"elevation","nlcdClass")]

derm$density<-((derm$adultCount+derm$nymphCount+derm$larvaCount)/derm$totalSampledArea)
derm<-derm[!is.na(derm$density),]

derm$adultdensity<-((derm$adultCount)/derm$totalSampledArea)

write.csv(derm,file="C:/Users/huangt/Documents/neon_Dermacentor_adult.csv")
```

#count dermencentor density
```{r}
derm$andensity<-((derm$adultCount+derm$nymphCount)/derm$totalSampledArea)
derm<-derm[!is.na(derm$andensity),]
write.csv(derm,file="C:/Users/huangt/Documents/neon_Dermacentor_an.csv")
```

#dermancentor density by LULC
```{r}
derm_a<-aggregate(derm,by=list(derm$nlcdClass),FUN=mean)
library(ggplot2)

jpeg("C:/Users/huangt/Documents/nlcd_adult.jpg")

b<-ggplot(derm,aes(x= derm$nlcdClass,y=derm$adultdensity,colours=derm$adultCount))+
   geom_bar(stat="identity", position=position_dodge())

b+ labs(x = "Land use",y="Adult tick count")+
  theme(axis.text.x=element_text(angle=90
                                 ,hjust=1,vjust=0.5
                                 ))
dev.off()

jpeg("C:/Users/huangt/Documents/nlcd_adult.jpg")

b<-ggplot(derm,aes(x= derm$nlcdClass,y=derm$andensity ,colours=derm$andensity))+
   geom_bar(stat="identity", position=position_dodge())

b+ labs(x = "Land use",y="Adult and nymph tick count")+
  theme(axis.text.x=element_text(angle=90
                                 ,hjust=1,vjust=0.5
                                 ))
dev.off()
```


```{r}
derm_site<-derm[,c("siteID","density"      ,"decimalLatitude"              ,"decimalLongitude"             ,"elevation")]
derm_site$siteID<-as.numeric(derm_site$siteID)
derm_site2<-aggregate(derm_site,by=list(derm_site$siteID),FUN=median)
write.csv(derm_site2,file="C:/Users/huangt/Documents/neon_Dermacentor_site4.csv")
```


#load library
```{r}
library(raster)
library(sp)
library(rgdal)
library("foreign")
library("ggplot2")
require("maptools")
require("plyr")
```

```{r}

loc_shp <- SpatialPointsDataFrame(derm[,c("decimalLongitude","decimalLatitude"              )],derm)   
plot(loc_shp)
```


